import { useEffect, useState } from 'react'
import { api } from '../../api/client'
import type { SchedulerStatus } from '../../types'

export default function SystemStatus() {
  const [status, setStatus] = useState<SchedulerStatus | null>(null)
  const [error, setError] = useState('')
  const [polling, setPolling] = useState(false)
  const [pollMsg, setPollMsg] = useState('')

  const load = () =>
    api.getStatus()
      .then(setStatus)
      .catch(e => setError(e.message))

  useEffect(() => { load() }, [])

  const handlePollNow = async () => {
    setPolling(true)
    setPollMsg('')
    try {
      const r = await api.pollNow()
      setPollMsg(r.message + ' — check Alert History in ~10 seconds.')
      setTimeout(load, 5000)
    } catch (e: unknown) {
      setPollMsg('Error: ' + (e instanceof Error ? e.message : String(e)))
    } finally {
      setPolling(false)
    }
  }

  const fmt = (dt: string | null) =>
    dt ? new Date(dt).toLocaleString() : '—'

  return (
    <div>
      <div className="page-header">
        <h1>System Status</h1>
        <p>Scheduler health, simulation mode indicator, and manual poll control.</p>
      </div>

      {error && <div className="error-banner">{error}</div>}
      {pollMsg && <div className="sim-banner">{pollMsg}</div>}

      {status ? (
        <>
          {status.sim_mode && (
            <div className="sim-banner">
              <strong>Simulation Mode is ON</strong> — No real Nextdoor API calls are being made.
              Posts are generated by the simulator. Set <code>SIM_MODE=false</code> and provide
              API credentials to use the official Nextdoor Search API.
            </div>
          )}

          <div className="card">
            <div className="card-header">
              <h2>Scheduler</h2>
              <button className="btn btn-primary" onClick={handlePollNow} disabled={polling}>
                {polling ? <><span className="spinner" /> Polling…</> : '▶ Poll Now'}
              </button>
            </div>
            <table>
              <tbody>
                <tr>
                  <td style={{ fontWeight: 600, width: 200 }}>Status</td>
                  <td>
                    <span className={`status-dot ${status.running ? 'green' : 'red'}`} />
                    {status.running ? 'Running' : 'Stopped'}
                  </td>
                </tr>
                <tr>
                  <td style={{ fontWeight: 600 }}>Mode</td>
                  <td>
                    {status.sim_mode
                      ? <span className="badge badge-yellow">Simulation</span>
                      : <span className="badge badge-green">Live API</span>}
                  </td>
                </tr>
                <tr>
                  <td style={{ fontWeight: 600 }}>Poll interval</td>
                  <td>{status.poll_interval_seconds}s ({Math.round(status.poll_interval_seconds / 60)} min)</td>
                </tr>
                <tr>
                  <td style={{ fontWeight: 600 }}>Next scheduled run</td>
                  <td>{fmt(status.next_run_time)}</td>
                </tr>
              </tbody>
            </table>
          </div>

          {status.last_run_result && (
            <div className="card">
              <h2 style={{ marginBottom: 16 }}>Last Poll Result</h2>
              <table>
                <tbody>
                  {Object.entries(status.last_run_result).map(([k, v]) => (
                    <tr key={k}>
                      <td style={{ fontWeight: 600, width: 200 }}>{k.replace(/_/g, ' ')}</td>
                      <td>{JSON.stringify(v)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {status.last_run_error && (
            <div className="error-banner">Last poll error: {status.last_run_error}</div>
          )}
        </>
      ) : (
        !error && <div className="empty"><span className="spinner" /></div>
      )}
    </div>
  )
}
